
require 'vendor/extensions/vintagesales/app/models/calculator/vintagesales_standard_calculator'
require 'vendor/extensions/vintagesales/app/models/calculator/vintagesales_priority_calculator'
require 'vendor/extensions/vintagesales/app/models/calculator/vintagesales_overnight_calculator'

Calculator::VintageSalesOvernightCalculator
Calculator::VintageSalesPriorityCalculator
Calculator::VintageSalesStandardCalculator
